name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Ejecutar tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests unitarios
        run: python3 -m unittest tests/*.py

  build-and-push:
    name: Publicar imagen en Docker Hub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y push de la imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}
